<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>KoH2Upscale</AssemblyName>
    <LangVersion>9.0</LangVersion>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GameDir Condition="'$(GameDir)' == ''">$(HOME)/.local/share/Steam/steamapps/common/Knights of Honor II</GameDir>
    <Managed>$(GameDir)/Sovereign_Data/Managed</Managed>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="$(GameDir)/BepInEx/core/BepInEx.dll" Private="false" />
    <Reference Include="$(GameDir)/BepInEx/core/0Harmony.dll" Private="false" />
    <Reference Include="$(Managed)/UnityEngine.dll" Private="false" />
    <Reference Include="$(Managed)/UnityEngine.CoreModule.dll" Private="false" />
    <Reference Include="$(Managed)/UnityEngine.IMGUIModule.dll" Private="false" />
    <Reference Include="$(Managed)/UnityEngine.InputLegacyModule.dll" Private="false" />
    <Reference Include="$(Managed)/UnityEngine.UIModule.dll" Private="false" />
    <Reference Include="$(Managed)/Unity.Postprocessing.Runtime.dll" Private="false" />
    <Reference Include="$(Managed)/Assembly-CSharp.dll" Private="false" />
    <Reference Include="$(Managed)/Assembly-CSharp-firstpass.dll" Private="false" />
    <Reference Include="$(Managed)/Sentry.dll" Private="false" />
    <Reference Include="$(Managed)/Sentry.Unity.dll" Private="false" />
  </ItemGroup>
  <Target Name="Deploy" AfterTargets="Build" Condition="'$(Deploy)' == 'true'">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(GameDir)/BepInEx/plugins/KoH2Upscale" />
  </Target>
</Project>
